paises_tupla= ("francia", "inglaterra","españa","alemania","australia")
print(paises_tupla)
print()
paises= input("porfavor introduzca uno de los paises de arriha")
print(paises,"tiene el numero de lista", paises_tupla.index(paises))